#!/usr/bin/env bash
# Base packages. Requires sudo — run it yourself in a terminal.
#
# Generated by the new-machine-setup skill. Safe to re-run.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_env-report.sh
. "$SCRIPT_DIR/_env-report.sh"

info() { printf '\033[36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[33mwarn:\033[0m %s\n' "$*"; }
die()  { printf '\033[31merror:\033[0m %s\n' "$*" >&2; exit 1; }

command -v apt-get >/dev/null || die "this script targets Debian/Ubuntu (no apt-get)"

PKGS=(zsh git curl wget tmux htop build-essential ca-certificates)

# Only install what is actually missing, so re-runs are quiet and fast.
MISSING=()
for p in "${PKGS[@]}"; do
  dpkg -s "$p" >/dev/null 2>&1 || MISSING+=("$p")
done

# gh lives in universe on recent Ubuntu; fall back to GitHub's own repo.
if ! command -v gh >/dev/null 2>&1; then
  if apt-cache show gh >/dev/null 2>&1; then
    MISSING+=(gh)
  else
    info "gh not in the configured repos — adding GitHub's apt source"
    sudo mkdir -p -m 755 /etc/apt/keyrings
    wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg \
      | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg >/dev/null
    sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" \
      | sudo tee /etc/apt/sources.list.d/github-cli.list >/dev/null
    MISSING+=(gh)
  fi
fi

if [ ${#MISSING[@]} -eq 0 ]; then
  info "everything already installed — nothing to do"
else
  info "installing: ${MISSING[*]}"
  sudo apt-get update
  sudo apt-get install -y "${MISSING[@]}"
fi

printf '\n'
info "done. Verify:"
for c in zsh git curl wget tmux htop gh gcc; do
  if command -v "$c" >/dev/null 2>&1; then
    printf '    \033[32m✓\033[0m %s\n' "$c"
  else
    printf '    \033[31m✗\033[0m %s\n' "$c"
  fi
done

env_report

printf '\033[1mNEXT:\033[0m  ./2-shell-and-conda.sh   (no sudo needed)\n'
