#!/usr/bin/env bash
# Shell + Python environment. No sudo except the chsh prompt.
#
# Generated by the new-machine-setup skill. Safe to re-run.

set -euo pipefail

# --- generated config -----------------------------------------------------
CONDA_PREFIX_DIR="@@CONDA_PREFIX_DIR@@"
HF_HOME_DIR="@@HF_HOME_DIR@@"
# --------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_env-report.sh
. "$SCRIPT_DIR/_env-report.sh"

info() { printf '\033[36m==>\033[0m %s\n' "$*"; }
skip() { printf '\033[90m -- %s\033[0m\n' "$*"; }
warn() { printf '\033[33mwarn:\033[0m %s\n' "$*"; }

# --- oh-my-zsh ------------------------------------------------------------
# MUST run before anything that appends to ~/.zshrc: the installer moves an
# existing .zshrc to .zshrc.pre-oh-my-zsh and writes a fresh one, which would
# silently orphan any lines added earlier.
if [ -d "$HOME/.oh-my-zsh" ]; then
  skip "oh-my-zsh already installed"
else
  command -v zsh >/dev/null || { warn "zsh missing — run ./1-packages.sh first"; exit 1; }
  info "installing oh-my-zsh"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
fi

# --- login shell ----------------------------------------------------------
if [ "$(basename "${SHELL:-}")" = "zsh" ]; then
  skip "login shell is already zsh"
else
  info "setting zsh as the login shell (this will ask for your password)"
  chsh -s "$(command -v zsh)" || warn "chsh failed — set it manually later, not fatal"
fi

# --- miniconda ------------------------------------------------------------
if [ -x "$CONDA_PREFIX_DIR/bin/conda" ]; then
  skip "miniconda already at $CONDA_PREFIX_DIR"
else
  info "installing miniconda to $CONDA_PREFIX_DIR"
  ARCH=$(uname -m)
  curl -fsSL -o /tmp/miniconda.sh \
    "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-${ARCH}.sh"
  bash /tmp/miniconda.sh -b -p "$CONDA_PREFIX_DIR"   # -b batch, -p prefix
  rm -f /tmp/miniconda.sh
fi

info "wiring conda into bash and zsh"
"$CONDA_PREFIX_DIR/bin/conda" init bash zsh >/dev/null

# Keep (base) out of every new shell — opt in with `conda activate base`.
# The key was renamed auto_activate_base -> auto_activate (conda 25.x). Newer
# conda still honours the old name as an alias, but that will not last, and
# older conda does not know the new one — so try new, fall back to old.
if ! "$CONDA_PREFIX_DIR/bin/conda" config --set auto_activate false 2>/dev/null; then
  "$CONDA_PREFIX_DIR/bin/conda" config --set auto_activate_base false
fi

# --- environment block ----------------------------------------------------
# Everything this setup exports lives in one marked block, so re-runs replace
# rather than append, and removal is a single sed.
mkdir -p "$HF_HOME_DIR"

# ~/.local/bin is where the Claude Code native installer puts `claude`. Ubuntu's
# stock .bashrc adds it; the .zshrc oh-my-zsh just wrote leaves it commented
# out — so `claude` works in bash and disappears the moment you `exec zsh`.
# Managing it here fixes zsh and is a no-op for bash (the guard skips a dir
# already on PATH).
LOCAL_BIN="$HOME/.local/bin"
mkdir -p "$LOCAL_BIN"

for rc in "$HOME/.bashrc" "$HOME/.zshrc"; do
  [ -f "$rc" ] || continue
  env_block_write "$rc" "HF_HOME=$HF_HOME_DIR" "PATH+=$LOCAL_BIN"
  info "environment block written to $rc"
done

if [ ! -x "$LOCAL_BIN/claude" ] && ! command -v claude >/dev/null 2>&1; then
  warn "claude not found — PATH is wired, but install it with:"
  warn "  curl -fsSL https://claude.ai/install.sh | bash"
fi

# --- report ---------------------------------------------------------------
env_report

printf '\033[1mNEXT:\033[0m  exec zsh          # load the new shell + env\n'
printf '        ./3-logins.sh     # Hugging Face + GitHub (interactive)\n'
