#!/usr/bin/env bash
# Hugging Face + GitHub authentication. Interactive by design — this is why it
# is a script you run rather than something the agent drives: both CLIs need a
# real terminal, and neither token should ever land in an agent transcript.
#
# Generated by the new-machine-setup skill. Safe to re-run.

set -euo pipefail

# --- generated config -----------------------------------------------------
CONDA_PREFIX_DIR="@@CONDA_PREFIX_DIR@@"
GIT_NAME="@@GIT_NAME@@"
GIT_EMAIL="@@GIT_EMAIL@@"
# --------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_env-report.sh
. "$SCRIPT_DIR/_env-report.sh"

info() { printf '\033[36m==>\033[0m %s\n' "$*"; }
skip() { printf '\033[90m -- %s\033[0m\n' "$*"; }
warn() { printf '\033[33mwarn:\033[0m %s\n' "$*"; }

PIP="$CONDA_PREFIX_DIR/bin/pip"
HF="$CONDA_PREFIX_DIR/bin/hf"
[ -x "$PIP" ] || { PIP=$(command -v pip3 || command -v pip); HF=$(command -v hf || echo hf); }

# --- hugging face ---------------------------------------------------------
if ! [ -x "$HF" ] && ! command -v hf >/dev/null 2>&1; then
  info "installing the huggingface_hub CLI"
  "$PIP" install -q -U "huggingface_hub[cli]"
  HF="$CONDA_PREFIX_DIR/bin/hf"
  [ -x "$HF" ] || HF=$(command -v hf)
fi

if "$HF" auth whoami >/dev/null 2>&1; then
  skip "Hugging Face: already logged in as $("$HF" auth whoami 2>/dev/null | head -1)"
else
  printf '\n\033[1mHugging Face login\033[0m\n'
  printf '  Get a token (write scope) from https://huggingface.co/settings/tokens\n'
  printf '  Answer Y to "add token as git credential" if you push models or datasets.\n'
  printf '  The token is stored under $HF_HOME, not in any rc file.\n\n'
  "$HF" auth login
fi

# --- git identity ---------------------------------------------------------
if [ -n "$GIT_NAME" ]; then
  git config --global user.name "$GIT_NAME"
fi
git config --global user.email "$GIT_EMAIL"
git config --global init.defaultBranch main
info "git identity: $(git config --global user.name || echo '<unset>') <$(git config --global user.email)>"

# --- github ---------------------------------------------------------------
if gh auth status >/dev/null 2>&1; then
  skip "GitHub: already authenticated"
else
  printf '\n\033[1mGitHub login\033[0m\n'
  printf '  Desktop: GitHub.com -> SSH -> generate a new key -> login with a browser.\n'
  printf '  Headless: choose "paste an authentication token" instead\n'
  printf '            (https://github.com/settings/tokens).\n\n'
  gh auth login
fi

gh auth setup-git   # let git use gh's credentials for HTTPS remotes

# If gh knows the account and no git name was configured, adopt it.
if [ -z "$(git config --global user.name || true)" ]; then
  GH_USER=$(gh api user --jq .name 2>/dev/null || true)
  [ -n "$GH_USER" ] && { git config --global user.name "$GH_USER"; info "git user.name set from GitHub: $GH_USER"; }
fi

printf '\n'
info "authentication complete"
printf '    hf:  %s\n' "$("$HF" auth whoami 2>/dev/null | head -1 || echo 'not logged in')"
printf '    gh:  %s\n' "$(gh auth status 2>&1 | grep -o 'account [^ ]*' | head -1 || echo 'not logged in')"
printf '    \033[90mtokens live in $HF_HOME/token and gh'"'"'s own store — never in an rc file\033[0m\n'

env_report

printf '\033[1mNEXT:\033[0m  @@NEXT_STEP@@\n'
